employees = [
    {
        "id": 1,
        "first_name": "Ankur",
        "last_name": "Tiwari",
        "email": "ankur@gmail.com",
        "phone": "9876543210",
        "department": "Engineering",
        "designation": "Senior Software Engineer",
        "salary": 120000,
        "experience": 5.5,
        "is_active": True,
        "skills": ["React", "Node.js", "FastAPI"],
        "address": {"city": "Bhopal", "state": "Madhya Pradesh", "country": "India"},
    },
    {
        "id": 2,
        "first_name": "Rahul",
        "last_name": "Sharma",
        "email": "rahul@gmail.com",
        "phone": "9876543211",
        "department": "QA",
        "designation": "QA Engineer",
        "salary": 80000,
        "experience": 3,
        "is_active": True,
        "skills": ["Selenium", "Postman"],
        "address": {"city": "Indore", "state": "Madhya Pradesh", "country": "India"},
    },
]
